version: '3'
      
volumes:
  db:

services:

  db:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'